### ISSUE TITLE
I believe the Angular packages need an upgrade.

### ISSUE THREAD

**Issue by Abhipray04** [kkoripl/NaryaKeyPointsDatasetCreator#4]
Hi there,

Thanks for your brilliant repo. While I was trying to make it run on my local machine with Custom Sport, it struggled with the Node.js version and various Angular packages. 

> C:\Repos\NaryaKeyPointsDatasetCreator\frontend>ng serve --c=local
Node.js version v12.22.12 detected.
The Angular CLI requires a minimum Node.js version of v18.13.

if I try a new Node.js version, it throws a new error:

> 10% building 3/3 modules 0 active(node:8568) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
10% building 3/6 modules 3 active ...setCreator\frontend\node_modules\@angular\material\prebuilt-themes\indigo-pink.cssC:\Repos\NaryaKeyPointsDatasetCreator\frontend\node_modules\loader-runner\lib\LoaderRunner.js:106
                        throw new Error("callback(): The callback was already called.");
                              ^
Error:` callback(): The callback was already called.
    at context.callback (C:\Repos\NaryaKeyPointsDatasetCreator\frontend\node_modules\loader-runner\lib\LoaderRunner.js:106:10)
    at C:\Repos\NaryaKeyPointsDatasetCreator\frontend\node_modules\css-loader\dist\index.js:137:5
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Node.js v19.9.0

Could you please look into it?

**Comment by Abhipray04** [comment]
Solved it by downgrading Node.js to a compatible version. Angular CLI 9 is compatible with Node.js versions 10-12. Used NVM to install a compatible version. 

> For instance, you could install Node.js version 12.14.1:

`nvm install 12.14.1`
`nvm use 12.14.1`


and then reinstall the dependencies.
